### ISSUE TITLE
Shorter email alias for contacting psf org admins

### ISSUE THREAD

**Issue by terriko** [python-gsoc/gsoc#10]
I get a lot of GSoC-related emails sent only to me that would probably be handled faster if they went to all the org admins.  Part of the reason for this is that it's easier to find and remember my email address than the one we currently use to reach all org admins.

I'm proposing gsoc-admins@python.org set up as a mailing list for all the org admins.  It will need to be set up to accept all emails so no one has to moderate it, and should keep archives available only to the members of the list.

I'm opening an issue here to make sure I don't forget to do this once the 2016 program is announced.

**Comment by sils** [comment]
@terriko reminder, this seems to be resolved
