### ISSUE TITLE
Melange Submit and Yes do different actions without clarity

### ISSUE THREAD

**Issue by meflin** [python-gsoc/gsoc#12]
https://code.google.com/p/soc/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Stars%20Priority%20Status%20Type%20Owner%20Milestone%20Effort%20Skills%20Summary&groupby=&sort=&id=2530

**Comment by terriko** [comment]
Notes: this is a bug we hit a lot in 2015 at the PSF.  Typically, someone would change the accept drop-down, write a "thanks!" and hit the "submit" button assuming it would submit both their acceptance and the comment, when in reality it only submitted the comment.  It's also a bug that got Stephen in trouble when he made a bug report about it, so we need to be careful in how we work with the melange team on this.

I think, however, that they would be willing to accept a tested patch that improved the behaviour if we're friendly and super polite and approach them with functional code that they can merge during the off-season when they aren't swamped with angry bug reports.   Please talk to Terri before actually submitting code to melange.

Suggested fix: make it so there's only one submit button on that page and it updates both comments and role acceptance.

**Comment by terriko** [comment]
Since Melange is no longer going to be used in 2016 and the folk in charge of the new system have been totally awesome about working with org admins, I'm going to close this.  I'm sure we'll find new bugs, but hopefully not this one again!
