### ISSUE TITLE
Automated blog reminder emails

### ISSUE THREAD

**Issue by terriko** [python-gsoc/gsoc#13]
Currently, we rely upon mentors to keep an eye on how frequently their students are blogging and the org admins send out periodic reminders if it looks like a student is having trouble.  Unfortunately, those reminders are done manually, so they sometimes don't get sent if the org admins aren't available.  We'd like an automated script that checks the RSS feed and makes sure that the student has blogged on schedule, and sends a reminder email to the student, their mentors, and the org admins if they have not.

Ideally, this would be a python script that Terri could run on the same machine that runs the blog aggregation software.

**Comment by cpmydream** [comment]
Hey I can help if you want!1
I am looking some good work in python !!

**Comment by sils** [comment]
Hey, we actually had such a script for GNOME once, I may be able to dig that up as somebody sent it to me once...

**Comment by sils** [comment]
Hah, found it, apparently it just prints the dates when students have blogged for all students using feedparser. Don't know the license so I can't share it but it's nothing more than that really, very simple.

**Comment by hashhar** [comment]
I would like to work on this.
So please see if I got your requirements right.

You have a list of blogs of students somewhere. (Is it guaranteed that all blogs will have an atom or rss feed?)
You check the list periodically to see if a new blog post was created or not by the scheduled date.
If not, send an email to org admin, mentor and the student.

**Comment by terriko** [comment]
The list of this year's blogs are here: https://github.com/terriko/gsoc/blob/master/blog-aggregator-configs/config2016.ini  
Everyone on that feed is required to provide a valid atom or rss feed.  If it's not valid, that can be viewed the same way as not having a post (as in, it's a thing that the student should be warned about, although maybe with a different error message).

**Comment by hashhar** [comment]
Okay. I will try and work on it. Let's see what I can come up with.

EDIT: It seems to be working out. You can track my progress and suggest improvements [here](https://github.com/hashhar/gsoc-feedparser).

I'm taking byte sized steps. I can read the [config file](https://github.com/hashhar/gsoc-feedparser/blob/master/blogs.ini) (**_PLEASE SEE IF YOU NEED ANYTHING MORE IN THE CONFIG FILE, apart from organisation owner email and mentor email and student email.**_) and get the latest publish date of most blog posts. There seems to be an exception which I will look into later.

**Comment by hashhar** [comment]
I found one blog that didn't apparently have a feed of any kind set up. [https://tmrts.com/](https://tmrts.com/). I could manage to get the last-updated and posted dates. The part left to do is the sending email.

Please take a look at this file and tell me if any info (apart from student emails and mentor emails) are needed by my script. [config file](https://github.com/hashhar/gsoc-feedparser/blob/master/blogs.ini)

**Comment by hashhar** [comment]
I got email working. Where can I find the emails for the bloggers and the org members? The GSOC page? I think I'll be able to ship this to you with unit tests and all within the week.

**Comment by terriko** [comment]
I think we've got something in place for 2018, so I'm closing this issue for the moment!

**Comment by hashhar** [comment]
Well, it was a great learning exercise. If anyone is interested they can find my work at https://github.com/hashhar/gsoc-feedparser/tree/email
