### ISSUE TITLE
Prepare ideas for student projects early

### ISSUE THREAD

**Issue by terriko** [python-gsoc/gsoc#19]
(Via IRC from the most excellent Taggnostr)

 2) find projects for the students to do:
- check in the bug tracker for issues with the gsoc keyword
- check for approved but not-yet implemented PEPs/issues 
- check infrastructure-related projects
- ask coredevs and infra guys if they have projects

**Comment by PranayMukherjee** [comment]
Anything you people need implemented / added ?

**Comment by terriko** [comment]
@PranayMukherjee This year core python is taking the year off due to insufficient mentor availability, but you can check out our other sub-orgs here: http://python-gsoc.org/#ideas
