### ISSUE TITLE
GSOC 2016 Official Python Software Foundation Website

### ISSUE THREAD

**Issue by manishbisht** [python-gsoc/gsoc#21]
Hello Maam,

I want to make some contributions on Python Software Foundation. So I have one idea can we make the official website of the GSOC 2016 like on the domain gsoc16.python.org or the other domain you like. On that page all the details related to mentors and ideas will be put there and we can write there some useful tips for the students to get selected in GSOC 2016.
It will be very useful for the students and also we as the Python Software Foundation contributor have some place where all the details of the mentor and students can be kept.

Hope you will like this.

Thanks :)

**Comment by terriko** [comment]
First, everything you suggest content-wise will be on the wiki page here: https://wiki.python.org/moin/SummerOfCode/2016

The ideas and information there evolve as the program continues; I'm still waiting for ideas and mentoring information to come in as sub-orgs and mentors sign up.  But it's already full of links and tips, and more will be set up as we decide on things like the format for this year's application.

If you're just talking about having a shorter url, that's not a bad idea, but requires coordination with the infrastructure team.  I'll inquire but the lead time may be pretty long on that and it's not a high priority

**Comment by manishbisht** [comment]
@terriko Can we improve the design of the wiki. I want to implement some good designs on the wiki page :)

**Comment by terriko** [comment]
Are you trying to propose this as a potential GSoC project?  This is not suitable for that (there's not enough coding involved). And honestly, I don't have the volunteers necessary to work with you on it either way.  If you have specific concrete suggestions, we might consider them, but a general redesign is not something we're looking for this year.  Please focus your time on our sub-orgs who actually need help with their open issues instead!
