### ISSUE TITLE
Blog feed link not showing up in aggregator 

### ISSUE THREAD

**Issue by jdetle** [python-gsoc/gsoc#42]
Despite having the proper link in the init file, I don't have a link on the righthand of the page. Any chance that any of you wonderful people could help me with my problem?

**Comment by meflin** [comment]
https fails use http ... also on http I'm not seeing any of the required bloging about GSOC

**Comment by jdetle** [comment]
Okay, I'll try and make that fix. I have three posts up right now and am currently working on a fourth, jdetle.com. My project is to implement dimension reduction methods in MDAnalysis.

**Comment by jdetle** [comment]
How should I go about making it apparent that all these posts are pertinent to my GSoC work?

**Comment by meflin** [comment]
Mention Gsoc and the org/project you are working on and what you 
are coding. 

Meflin

**Comment by terriko** [comment]
Closing this since it's leftover from last year.
