### ISSUE TITLE
Close down the robot

### ISSUE THREAD

**Issue by J08nY** [python-gsoc/gsoc#85]
I was a part of the 2017 PSF GSoC project, so back then I added my blog to the 2017 blog tracker. However, I added a blog which I use regularly. Now, long after the 2017 GSoC projects ended, the PSF GSoC scraper is still scraping my blog, while I would like it to stop. Could this repository be closed down and the scraper stopped, when obviously some different infrastructure is used from 2018 on? @terriko 

    23.128.96.11 - - [08/Feb/2019:23:45:19 +0100] "GET /recent.atom HTTP/1.1" 200 52967 "-" "Python's Summer of Code 2017 Updates +http://blogs.python-gsoc.org Planet/2.0 +http://www.planetplanet.org UniversalFeedParser/5.2.1 +https://code.google.com/p/feedparser/"

**Comment by terriko** [comment]
I thought I'd closed that down!  Thanks for letting me know.  I can't log in to that machine from here, but I'll try to get it shut down this weekend.

**Comment by terriko** [comment]
I turned this off a couple of days ago.  Sorry about the delay, I've been sick a lot the past month!
