### ISSUE TITLE
Add gitter support

### ISSUE THREAD

**Issue by terriko** [python-gsoc/gsoc#86]
Potential idea: We're at the point where nearly as many projects use gitter as use IRC.  

It looks like gitter has an IRC bridge https://irc.gitter.im/ and clients for OSX, iOS, Android, Windows and Linux.  

(Reasoning: our current setup with IRC bridged to Matrix and Slack is requiring some manual intervention to support.  We could consider replacing both Matrix and Slack in favour of gitter if the bridge requires less admin attention.)

**Comment by veb7vmehra** [comment]
Hi @terriko, I am new here and am interested in working on this issue. I think it is all about taking PSF to gitter chatroom or is there something else also? Also I am interested in working for python-gsoc so can you tell me about any prerequisites required.

**Comment by terriko** [comment]
I don't think this is one a student can work on right now, sorry!  We've got it up and running, but their android app support isn't quite where we need it to be, and instead we had some success with fixing our matrix problem, so we'll be going that route instead.  I'll close this issue.
